Add commons-io dependency to snap-core and remove from opttbx-s2msi-reader
This should resolve the issue when a module depends on s2msi-reader, snap-core and commons-io. In this case the module does not know where to load the classes from.
java.lang.ClassNotFoundException: Will not load class org.apache.commons.io.input.ReversedLinesFileReader arbitrarily from one of ModuleCL@4bc08f13[eu.esa.opt.opttbx.s2msi.reader] and ModuleCL@29091e7a[org.esa.snap.snap.core] starting from ModuleCL@e56c0cf[org.eomasters.eomtbx]

Moved commons-io dependency from opttbx-s2msi-reader to snap-core to centralize its usage. This ensures consistent versioning across modules and avoids redundancy.